name: beercrackerz
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_settings_ui: ^3.0.0
  flutter_map: ^6.1.0
  flutter_map_location_marker: ^8.0.8
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.3
  geolocator: ^11.0.0
  http: ^1.2.0
  latlong2: ^0.9.0
  url_launcher: ^6.2.5
  toggle_switch: ^2.1.0
  flutter_secure_storage: ^9.0.0
  toastification: ^1.2.1
  loader_overlay: ^4.0.0
  image_picker: ^1.1.0
  image_cropper: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/marker/
    - assets/images/icon/
